// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PClinicPOS.Api.Data;

#nullable disable

namespace PClinicPOS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250212120000_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");
            modelBuilder.UseIdentityByDefaultColumns();
            // Snapshot omitted for manual migration; model is applied via SQL in Initial.Up()
#pragma warning restore 612, 618
        }
    }
}
